### ISSUE TITLE
Bug: Eltern registrieren funktioniert nicht.

### ISSUE THREAD

**Issue by Rumpelstilzli** [Rumpelstilzli/morea#12]
Es fehlt groupID

Nein, das soll so sein!
Eltern "folgen" kinder. Kinder "folgen" gruppen.
Die Eltern bekommen die GroupIDs mit dem Lesen der Kinder mit. Grund dafür: Kinder können Gruppen ändern. 
-d

**Comment by roranmorea** [comment]
@Rumpelstilzli 
Aber dann gibt es einen Fehler auf der HomePage, denn die braucht die groupID.
Dann müssen wir das noch anpassen für Eltern. # #

**Comment by Rumpelstilzli** [comment]
Bei meiner Version habe ich dies implementiert. Der Elternteil kommt auf ein Screen, der ihm sagt, er soll ins Profil und dort sich mit einem Kind verbinden oder eins registrieren.
![grafik](https://user-images.githubusercontent.com/32130052/70780867-ccad8080-1d85-11ea-8637-52276b6d0c4a.png)
![grafik](https://user-images.githubusercontent.com/32130052/70780892-da630600-1d85-11ea-8a9d-2152a5f8bf35.png)
![grafik](https://user-images.githubusercontent.com/32130052/70780906-e2bb4100-1d85-11ea-8955-e7ab4da81367.png)

**Comment by roranmorea** [comment]
Ok aber dann ist deine Version nicht auf dem master-branch, weil bei mir geht es nicht. Wenn ich neue Eltern zu registrieren versuche, dann kommt erst ein Fehler bei Registrierung, dann wird nur ein Account erstellt, aber keine Account Informationen werden in der Datenbank gespeichert und dadurch kann dann auch nichts angezeigt werden im Homescreen.

Performing hot restart...
Syncing files to device SM G960F...
Restarted application in 1’460ms.
I/flutter (22245): get Doc: user/cgsHhUvv2KgtCMgKRFufcyg3vkw1
E/flutter (22245): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method 'forEach' was called on null.
E/flutter (22245): Receiver: null
E/flutter (22245): Tried calling: forEach(Closure: (dynamic, dynamic) => Null)
E/flutter (22245): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter (22245): #1      new LinkedHashMap.from (dart:collection/linked_hash_map.dart:88:11)
E/flutter (22245): #2      MoreaFirebase.getData (package:morea/services/morea_firestore.dart:66:14)
E/flutter (22245): <asynchronous suspension>
E/flutter (22245): #3      _RootPageState.initMoreaFire (package:morea/Pages/Grundbausteine/root_page.dart:65:26)
E/flutter (22245): <asynchronous suspension>
E/flutter (22245): #4      _RootPageState.authStatusInit (package:morea/Pages/Grundbausteine/root_page.dart:74:13)
E/flutter (22245): <asynchronous suspension>
E/flutter (22245): #5      _RootPageState.initState (package:morea/Pages/Grundbausteine/root_page.dart:50:5)
E/flutter (22245): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4068:58)
E/flutter (22245): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter (22245): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (22245): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (22245): #10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter (22245): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (22245): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (22245): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (22245): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (22245): #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter (22245): #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter (22245): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (22245): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (22245): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter (22245): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (22245): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (22245): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter (22245): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (22245): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (22245): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter (22245): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (22245): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (22245): #28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter (22245): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (22245): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (22245): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (22245): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (22245): #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter (22245): #34     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
E/flutter (22245): #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter (22245): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (22245): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (22245): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (22245): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (22245): #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter (22245): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter (22245): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (22245): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (22245): #44     ComponentElem

**Comment by Rumpelstilzli** [comment]
Version Error, schaue ob es jetzt besser ist

**Comment by roranmorea** [comment]
Ok werde ich machen.
Du solltest wirklich mit anderen Branches arbeiten als mit dem Masterbranch. In den Masterbranch sollten wir nur dann mergen wenn wir beide den neuen Branch getestet haben.

**Comment by roranmorea** [comment]
habe es getestet funktioniert bei mir
