### ISSUE TITLE
Bug: flutter 1.12.13

### ISSUE THREAD

**Issue by Rumpelstilzli** [Rumpelstilzli/morea#13]
After upgrading flutter to 1.12.13 flutter throw this error:

> Launching lib\main.dart on Android SDK built for x86 in debug mode...
Note: C:\Users\David Wild\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_core-0.4.2+1\android\src\main\java\io\flutter\plugins\firebase\core\FirebaseCorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\David Wild\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.12.11\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\David Wild\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.12.11\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Users\David Wild\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\qrcode_reader-0.4.4\android\src\main\java\com\matheusvillela\flutter\plugins\qrcodereader\QRCodeReaderPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Users\David Wild\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\share-0.6.3+4\android\src\main\java\io\flutter\plugins\share\SharePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
C:\Users\David Wild\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\shared_preferences-0.5.4+8\android\src\main\java\io\flutter\plugins\sharedpreferences\SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
                        ^
1 warning
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
√ Built build\app\outputs\apk\debug\app-debug.apk.
Flutter is taking longer than expected to report its views. Still trying...
E/flutter (10255): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.E/flutter (10255): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
E/flutter (10255): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
E/flutter (10255): #0      defaultBinaryMessenger.<anonymous closure> 
package:flutter/…/services/binary_messenger.dart:76
E/flutter (10255): #1      defaultBinaryMessenger 
package:flutter/…/services/binary_messenger.dart:89
E/flutter (10255): #2      MethodChannel.binaryMessenger 
package:flutter/…/services/platform_channel.dart:140
E/flutter (10255): #3      MethodChannel.setMethodCallHandler 
package:flutter/…/services/platform_channel.dart:368
E/flutter (10255): #4      new Firestore 
package:cloud_firestore/src/firestore.dart:13
E/flutter (10255): #5      main 
package:morea/main.dart:22
E/flutter (10255): #6      _runMainZoned.<anonymous closure>.<anonymous closure>  (dart:ui/hooks.dart:239:25)
E/flutter (10255): #7      _rootRun  (dart:async/zone.dart:1126:13)
E/flutter (10255): #8      _CustomZone.run  (dart:async/zone.dart:1023:19)
E/flutter (10255): #9      _runZoned  (dart:async/zone.dart:1518:10)
E/flutter (10255): #10     runZoned  (dart:async/zone.dart:1502:12)
E/flutter (10255): #11     _runMainZoned.<anonymous closure>  (dart:ui/hooks.dart:231:5)
E/flutter (10255): #12     _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:307:19)
E/flutter (10255): #13     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:174:12)
E/flutter (10255):

>

**Comment by roranmorea** [comment]
konnte dieses Problem behoben werden?

**Comment by Rumpelstilzli** [comment]
Arbeite zurzeit mit alter Version. Denke dieses Problem hat noch keine Priorität. Ok wenn ich dies in den Weihnachtsferien angehe?

**Comment by Rumpelstilzli** [comment]
Konnte es lösen, Problem wird hier beschriben : https://stackoverflow.com/questions/57689492/flutter-unhandled-exception-servicesbinding-defaultbinarymessenger-was-accesse

Bei uns war das Erzeugen des objektes Firebase vor runApp das Problem. 

``WidgetsFlutterBinding.ensureInitialized(); ``

Hatt aus irgend einem Grund nicht geklappt, nach runApp funktioniert es aber.
