### ISSUE TITLE
Nicht alles Packages funktionieren in iOS

### ISSUE THREAD

**Issue by roranmorea** [Rumpelstilzli/morea#15]
IOS- Version, alle Packages funktionieren ausser:
- cloud_messaging
 - Barcodescan (irgend welche in Rechte in der info.plist)

**Comment by Rumpelstilzli** [comment]
Doch Barcode funktioniert voll unfänglich. Bei cloud_messaging konnte ich den Dev token lesen. Dies sollte bedeuten, dass es funktioniert. Alles getestet ist es aber noch nicht. Wie hast du IOS ausprobiert?

**Comment by Rumpelstilzli** [comment]
@roranmorea ios build funktioniert nun auf dem Simulator!!! testen müsste  man auf einem echten Gerät um sicherzustellen, dass das scannen von Qr-codes funktioniert. Dafür brauche ich ein Iphone / ipad

**Comment by Rumpelstilzli** [comment]
@roranmorea die Packages funktionieren jetzt.
