### ISSUE TITLE
ProfilePage: Änderung über Function speichern

### ISSUE THREAD

**Issue by roranmorea** [Rumpelstilzli/morea#16]
Aber indirekt über ein Request, der von einer Google Function ausgeführt wird.
R

**Comment by Rumpelstilzli** [comment]
Das gitz scho?

**Comment by roranmorea** [comment]
Ja...

**Comment by roranmorea** [comment]
Werde einen Text unter dem FloatingActionButton hinzufügen und das Speichern der Änderungen über eine Function machen.

**Comment by roranmorea** [comment]
Kurze Frage @Rumpelstilzli :
Werden alle User keine Permission haben um im user-file zu schreiben oder nur die Teilnehmer/Eltern?
Und es wird nur der user-file gesperrt oder?

**Comment by roranmorea** [comment]
siehe #32

**Comment by roranmorea** [comment]
siehe #36
