### ISSUE TITLE
Fehler beim öffnen der Agenda Seite

### ISSUE THREAD

**Issue by roranmorea** [Rumpelstilzli/morea#18]
Die Agenda Seite wird richtig angezeigt, aber es wird folgender Fehler in der Konsole angezeigt:

I/flutter (22245): stream doc: groups/3775
E/flutter (22245): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter 'iterator' was called on null.
E/flutter (22245): Receiver: null
E/flutter (22245): Tried calling: iterator
E/flutter (22245): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter (22245): #1      Agenda.deleteAgendaEvent (package:morea/services/agenda.dart:45:27)
E/flutter (22245): <asynchronous suspension>
E/flutter (22245): #2      _AgendaStatePage.altevernichten (package:morea/Pages/Agenda/Agenda_page.dart:74:14)
E/flutter (22245): #3      _AgendaStatePage.Agenda.<anonymous closure>.<anonymous closure> (package:morea/Pages/Agenda/Agenda_page.dart:366:29)
E/flutter (22245): #4      new ListView.separated.<anonymous closure> (package:flutter/src/widgets/scroll_view.dart:1037:34)
E/flutter (22245): #5      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:442:15)
E/flutter (22245): #6      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1153:67)
E/flutter (22245): #7      _HashMap.putIfAbsent (dart:collection-patch/collection_patch.dart:137:29)
E/flutter (22245): #8      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1153:26)
E/flutter (22245): #9      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1166:55)
E/flutter (22245): #10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2328:19)
E/flutter (22245): #11     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1159:11)
E/flutter (22245): #12     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:354:23)
E/flutter (22245): #13     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1797:58)
E/flutter (22245): #14     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:875:15)
E/flutter (22245): #15     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1797:13)
E/flutter (22245): #16     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:343:5)
E/flutter (22245): #17     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:427:5)
E/flutter (22245): #18     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:78:12)
E/flutter (22245): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (22245): #20     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:181:11)
E/flutter (22245): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (22245): #22     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:406:13)
E/flutter (22245): #23     RenderShrinkWrappingViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1681:12)
E/flutter (22245): #24     RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1644:20)
E/flutter (22245): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (22245): #26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (22245): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (22245): #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (22245): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (22245): #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (22245): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (22245): #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (22245): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (22245): #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (22245): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (22245): #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (22245): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (22245): #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (22245): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (22245): #40     RenderProxyBoxMixin.performLayout (pa
E/flutter (22245): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter 'iterator' was called on null.
E/flutter (22245): Receiver: null
E/flutter (22245): Tried calling: iterator
E/flutter (22245): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter (22245): #1      Agenda.deleteAgendaEvent (package:morea/services/agenda.dart:45:27)
E/flutter (22245): <asynchronous suspension>
E/flutter (22245): #2      _AgendaStatePage.altevernichten (package:morea/Pages/Agenda/Agenda_page.dart:74:14)
E/flutter (22245): #3      _AgendaStatePage.Agenda.<anonymous closure>.<anonymous closure> (package:morea/Pages/Agenda/Agenda_page.dart:366:29)
E/flutter (22245): #4      new ListView.separated.<anonymous closure> (package:flutter/src/widgets/scroll_view.dart:1037:34)
E/flutter (22245): #5      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:442:15)
E/flutter (22245): #6      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1153:67)
E/flutter (22245): #7      _HashMap.putIfAbsent (dart:collection-patch/collection_patch.dart:137:29)
E/flutter (22245): #8      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1153:26)
E/flutter (22245): #9      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1166:55)
E/flutter (22245): #10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2328:19)
E/flutter (22245): #11     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1159:11)
E/flutter (22245): #12     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:354:23)
E/flutter (22245): #13     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1797:58)
E/flutter (22245): #14     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:875:15)
E/flutter (22245): #15     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1797:13)
E/flutter (22245): #16     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:343:5)
E/flutter (22245): #17     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:489:5)
E/flutter (22245): #18     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:195:19)
E/flutter (22245): #19     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:238:19)
E/flutter (22245): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (22245): #21     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:181:11)
E/flutter (22245): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (22245): #23     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:406:13)
E/flutter (22245): #24     RenderShrinkWrappingViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1681:12)
E/flutter (22245): #25     RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1644:20)
E/flutter (22245): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (22245): #27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (22245): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (22245): #29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (22245): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (22245): #31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (22245): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (22245): #33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (22245): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (22245): #35     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (22245): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (22245): #37     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (22245): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (22245): #39     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (22245): #40     RenderO
E/flutter (22245): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter 'iterator' was called on null.
E/flutter (22245): Receiver: null
E/flutter (22245): Tried calling: iterator
E/flutter (22245): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter (22245): #1      Agenda.deleteAgendaEvent (package:morea/services/agenda.dart:45:27)
E/flutter (22245): <asynchronous suspension>
E/flutter (22245): #2      _AgendaStatePage.altevernichten (package:morea/Pages/Agenda/Agenda_page.dart:74:14)
E/flutter (22245): #3      _AgendaStatePage.Agenda.<anonymous closure>.<anonymous closure> (package:morea/Pages/Agenda/Agenda_page.dart:366:29)
E/flutter (22245): #4      new ListView.separated.<anonymous closure> (package:flutter/src/widgets/scroll_view.dart:1037:34)
E/flutter (22245): #5      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:442:15)
E/flutter (22245): #6      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1153:67)
E/flutter (22245): #7      _HashMap.putIfAbsent (dart:collection-patch/collection_patch.dart:137:29)
E/flutter (22245): #8      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1153:26)
E/flutter (22245): #9      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1166:55)
E/flutter (22245): #10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2328:19)
E/flutter (22245): #11     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1159:11)
E/flutter (22245): #12     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:354:23)
E/flutter (22245): #13     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1797:58)
E/flutter (22245): #14     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:875:15)
E/flutter (22245): #15     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1797:13)
E/flutter (22245): #16     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:343:5)
E/flutter (22245): #17     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:489:5)
E/flutter (22245): #18     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:195:19)
E/flutter (22245): #19     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:238:19)
E/flutter (22245): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (22245): #21     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:181:11)
E/flutter (22245): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (22245): #23     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:406:13)
E/flutter (22245): #24     RenderShrinkWrappingViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1681:12)
E/flutter (22245): #25     RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1644:20)
E/flutter (22245): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (22245): #27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (22245): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (22245): #29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (22245): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (22245): #31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (22245): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (22245): #33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (22245): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (22245): #35     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (22245): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (22245): #37     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (22245): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (22245): #39     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (22245): #40     RenderO

**Comment by Rumpelstilzli** [comment]
Siehe Pull request @roranmorea

**Comment by roranmorea** [comment]
Folgender Fehler wird neuerdings angezeigt, aber nur bei Accounts von Eltern.

E/flutter ( 7126): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Invalid document reference. Document references must have an even number of segments, but groups has 1, null)
E/flutter ( 7126): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 7126): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
E/flutter ( 7126): <asynchronous suspension>
E/flutter ( 7126): #2      DocumentReference.snapshots.<anonymous closure> (package:cloud_firestore/src/document_reference.dart:127:37)
E/flutter ( 7126): #3      _runGuarded (dart:async/stream_controller.dart:805:24)
E/flutter ( 7126): #4      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:213:7)
E/flutter ( 7126): #5      _ControllerStream._createSubscription (dart:async/stream_controller.dart:818:19)
E/flutter ( 7126): #6      _StreamImpl.listen (dart:async/stream_impl.dart:472:9)
E/flutter ( 7126): #7      _StreamIterator._initializeOrDone (dart:async/stream_impl.dart:1004:30)
E/flutter ( 7126): #8      _StreamIterator.moveNext (dart:async/stream_impl.dart:991:12)
E/flutter ( 7126): #9      Agenda.getAgendaOverview (package:morea/services/agenda.dart)
E/flutter ( 7126): <asynchronous suspension>
E/flutter ( 7126): #10     Agenda.addToList (package:morea/services/agenda.dart:45:62)
E/flutter ( 7126): <asynchronous suspension>
E/flutter ( 7126): #11     Agenda.getTotalAgendaOverview (package:morea/services/agenda.dart:77:7)
E/flutter ( 7126): <asynchronous suspension>
E/flutter ( 7126): #12     _AgendaStatePage._getAgenda (package:morea/Pages/Agenda/Agenda_page.dart:66:19)
E/flutter ( 7126): <asynchronous suspension>
E/flutter ( 7126): #13     _AgendaStatePage.Agenda (package:morea/Pages/Agenda/Agenda_page.dart:336:17)
E/flutter ( 7126): #14     _AgendaStatePage.build (package:morea/Pages/Agenda/Agenda_page.dart:306:15)
E/flutter ( 7126): #15     StatefulElement.build (package:flutter/src/widgets/framework.dart:4047:27)
E/flutter ( 7126): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3941:15)
E/flutter ( 7126): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter ( 7126): #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter ( 7126): #19     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
E/flutter ( 7126): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter ( 7126): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 7126): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 7126): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter ( 7126): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter ( 7126): #25     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2348:33)
E/flutter ( 7126): #26     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:760:20)
E/flutter ( 7126): #27     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:280:5)
E/flutter ( 7126): #28     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033:15)
E/flutter ( 7126): #29     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:975:9)
E/flutter ( 7126): #30     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:891:5)
E/flutter ( 7126): #31     _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 7126): #32     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 7126): #33     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 7126): #34     _invoke (dart:ui/hooks.dart:249:10)
E/flutter ( 7126): #35     _drawFrame (dart:ui/hooks.dart:207:3)

**Comment by Rumpelstilzli** [comment]
Jetzt?

**Comment by roranmorea** [comment]
funktioniert
