### ISSUE TITLE
Teleblitz Formatierung

### ISSUE THREAD

**Issue by Rumpelstilzli** [Rumpelstilzli/morea#22]
Text Mitnehmen und Bemerkung werden abgeschnitten
![grafik](https://user-images.githubusercontent.com/32130052/70998854-84b99100-20d8-11ea-9926-9ca51f99d9aa.png)

**Comment by roranmorea** [comment]
Hast du das schon gefixt?

**Comment by roranmorea** [comment]
Habe es gefixt mit dem letzten Commit.
Bitte überprüfen @Rumpelstilzli

**Comment by Rumpelstilzli** [comment]
![grafik](https://user-images.githubusercontent.com/32130052/71087986-b5173300-219d-11ea-9294-87bf4daafe41.png)
Ja ist gut so, vieleicht für die Verion 2, Punkte und Text seperieren + Erstes String zeichen sollte kein [space] sein

**Comment by roranmorea** [comment]
Oh ja finde ich eine gute idee
