### ISSUE TITLE
Eltern und Kinder ansicht auf neues Layout aktualisieren und überprüfen, ob floating Action Buttons wirklich nicht benutzt werden können (z. B. Agenda)

### ISSUE THREAD

**Issue by Rumpelstilzli** [Rumpelstilzli/morea#23]
R

**Comment by Rumpelstilzli** [comment]
Die namen werden nur lokal geändert. Fehlt da was?

**Comment by roranmorea** [comment]
Welche Namen meinst du?

**Comment by Rumpelstilzli** [comment]
Sry habe dein Code nicht verstanden.
Mann muss auf den Floatingactionbutton drücken um die Änderungen im System durchzuführen.
![grafik](https://user-images.githubusercontent.com/32130052/71075593-9fe1da80-2184-11ea-9bed-72117af8f968.png)
Das war mir nicht klahr. Finde dies ist irgendwie irreführend. Da muss noch ein Dialogfenster hin, das eim auf den floating action button aufmerksam macht. Zudem muss das ganze über eine Firebase-function geschehen. Die User werden kein write Zugriff auf die Collection "user" haben.

**Comment by roranmorea** [comment]
Oh ja stimmt habe das vergessen
