### ISSUE TITLE
Messaging

### ISSUE THREAD

**Issue by Rumpelstilzli** [Rumpelstilzli/morea#24]
R

**Comment by Rumpelstilzli** [comment]
Beim öffnen des Tabs Nachrichten erscheint bei mir dies:
![grafik](https://user-images.githubusercontent.com/32130052/71004798-bc2d3b00-20e2-11ea-8acc-4aadfd3e4e59.png)

Wie sieht der Stand der Dinge bei Messaging aus?

**Comment by roranmorea** [comment]
Funktionier bei mir...

**Comment by roranmorea** [comment]
Mit welchem Account versuchst es du auf diesem Bild?
Könntest du mir die uid geben?

**Comment by roranmorea** [comment]
Habe es nun gefixt glaube ich.
Wenn du keine Nachrichten hast, dann zeigt es jetzt "Keine Nachrichten vorhanden" an.
Bitte überprüfen @Rumpelstilzli

**Comment by Rumpelstilzli** [comment]
Funktioniert nun
