### ISSUE TITLE
_homeFeedMainEventID to List

### ISSUE THREAD

**Issue by Rumpelstilzli** [Rumpelstilzli/morea#28]
Das Feld in userMap namens "homeFeed" beinhaltet eine Liste von eventID Strings. _homeFeedMainEventID nimmt das Element 0 der Liste. 
Aus diesem Grund muss der Code so geschrieben werden, dass mehrere Events berücksichtigt werden können

**Comment by Rumpelstilzli** [comment]
im neusten Push im dev weg

**Comment by roranmorea** [comment]
kann es leider nicht überprüfen, weil es bei mir ein Error gibt, weil der `Access` Eintrag im `groups `document fehlt --> HomePage kann nicht geladen werden.
