### ISSUE TITLE
Device Token

### ISSUE THREAD

**Issue by Rumpelstilzli** [Rumpelstilzli/morea#29]
Der Device Token wird zur Zeit nicht in der Firebase abgespeichert. Ursprunglich mal im Home State. 
Überdenken von folgendem:

- Speicherort in der Database (unter groups oder im userProfile als Liste?)
- An welcher Programm stelle abfangen, z.B wenn man vom Registrieren in die Root-page weitergeleitet wird.

**Comment by roranmorea** [comment]
Oh ja dann müssen wir uns um das kümmern. Fürs Messaging ist es von Vorteil, wenn wir den Token in den Groups speichern. Ich denke wir sollten ihn an beidem Orten speichern.

**Comment by Rumpelstilzli** [comment]
@roranmorea für das Speicher im UserMap schreibe ich eine Cloud-Function. Der group - verteiler sollte meiner Meinung nach ebenfals über eine Cloud function geschehen. Oder Einfacher: wir machen ein Tab im Navigation drawer namens Einstellung, dort kann man Nachrichten einstellen

**Comment by Rumpelstilzli** [comment]
@roranmorea Die Funktion:
`subscribeToGroup(String groupID)`
fügt den device Token unter: `groups/{groupID}/Devices/{userID}`.
Die Funktion ist implementiert beim Login und dem CreateChildAndPendIt.
Noch zu implementieren ist eine die den Device Token als cloud function bei parentSentsRequeststring hinzufügt. Ebenfalls eine cloud Funktion die überprüft ob die Gruppe gewechselt wurde ist noch zu implementieren.

**Comment by roranmorea** [comment]
> @roranmorea für das Speicher im UserMap schreibe ich eine Cloud-Function. Der group - verteiler sollte meiner Meinung nach ebenfals über eine Cloud function geschehen. Oder Einfacher: wir machen ein Tab im Navigation drawer namens Einstellung, dort kann man Nachrichten einstellen

Ich denke für das Ändern der Gruppen können wir die ProfilePage nehmen.

**Comment by roranmorea** [comment]
> @roranmorea Die Funktion:
> `subscribeToGroup(String groupID)`
> fügt den device Token unter: `groups/{groupID}/Devices/{userID}`.
> Die Funktion ist implementiert beim Login und dem CreateChildAndPendIt.
> Noch zu implementieren ist eine die den Device Token als cloud function bei parentSentsRequeststring hinzufügt. Ebenfalls eine cloud Funktion die überprüft ob die Gruppe gewechselt wurde ist noch zu implementieren.

Ich wollte eh noch fragen wie das ist, wenn ein Elternteil sein Kind verknüpft. Was wird da alles gemacht?

**Comment by roranmorea** [comment]
@Rumpelstilzli gibt es hier etwas zu überprüfen?
