### ISSUE TITLE
App walkthrough - Tutorial für neue User

### ISSUE THREAD

**Issue by roranmorea** [Rumpelstilzli/morea#41]

**Comment by roranmorea** [comment]
@Rumpelstilzli 
Ich würde vorschlagen, dass wir einen Eintrag im Firestore machen, z. B. mit dem Namen <bool>"Tutorial". Wenn dieser Eintrag `true` ist, dann wird das Tutorial gestartet, sonst nicht.
Als Tutorial würde ich es machen, wie die meisten Apps, man wird Schritt für Schritt durch die App geführt und die verschiedenen Funktionen werden "gehighlighted" und mit einem Text unten am Bildschirm erklärt.

**Comment by Rumpelstilzli** [comment]
Ok, im userMap?

**Comment by roranmorea** [comment]
> Ok, im userMap?

Ja, ausser du bist nicht einverstanden oder hast einen anderen Vorschlag.

**Comment by Rumpelstilzli** [comment]
Nö, mach userMap




Holen Sie sich Outlook für Android







On Tue, Jan 7, 2020 at 4:28 PM +0100, "Massimiliano Grifone" <notifications@github.com> wrote:













Ok, im userMap?



Ja, ausser du bist nicht einverstanden oder hast einen anderen Vorschlag.

**Comment by roranmorea** [comment]
f1ab0debafcf6c98ffe443d9c07737671e5e3ec6
2f4d43a40472c6f042b5e94a8326ace5c1ddd9b3
fertig
