### ISSUE TITLE
Anmelde Listener

### ISSUE THREAD

**Issue by Rumpelstilzli** [Rumpelstilzli/morea#42]
> @roranmorea ah dem bisch du?

jap

_Originally posted by @roranmorea in https://github.com/Rumpelstilzli/morea/issues/21#issuecomment-567992291_

**Comment by Rumpelstilzli** [comment]
@roranmorea gits das jetzt?

**Comment by roranmorea** [comment]
> @roranmorea gits das jetzt?

@Rumpelstilzli jap
siehe folgenden durchgeführten Pull request #27

**Comment by Rumpelstilzli** [comment]
@roranmorea Reden wir von der gleichen Idee? Falls ja, haben wir ein puff mit den branches. 
Was ich unter Anmelde Listener verstehe, ist eine Funktion, die den Anmeldestatus eines TN's überprüft. Als Rückgabe wert hätte diese Funktion z.B. Angemolden, Abgemolden, undefiniert. Dieses würde auf dem Teleblitz Widget angezeigt werden.

**Comment by roranmorea** [comment]
> @roranmorea Reden wir von der gleichen Idee? Falls ja, haben wir ein puff mit den branches.
> Was ich unter Anmelde Listener verstehe, ist eine Funktion, die den Anmeldestatus eines TN's überprüft. Als Rückgabe wert hätte diese Funktion z.B. Angemolden, Abgemolden, undefiniert. Dieses würde auf dem Teleblitz Widget angezeigt werden.

Ja ich habe aus dem Teleblitz Container ein FlipCard gemacht. Auf der Rückseite steht bei Leitern wer sich an-/abgemeldet hat.

**Comment by roranmorea** [comment]
![Screenshot_20200108-142810](https://user-images.githubusercontent.com/48161365/71982297-71f03300-3224-11ea-87d1-98e24e8bc464.jpg)
![Screenshot_20200108-142812](https://user-images.githubusercontent.com/48161365/71982298-71f03300-3224-11ea-9fbd-08acd70a3cc0.jpg)

**Comment by Rumpelstilzli** [comment]
@roranmorea Du oder ich?
