### ISSUE TITLE
Message Groups ersatz

### ISSUE THREAD

**Issue by Rumpelstilzli** [Rumpelstilzli/morea#43]
Nei muss ahpasst werde

_Originally posted by @Rumpelstilzli in https://github.com/Rumpelstilzli/morea/pull/37/review_comment/create_

**Comment by Rumpelstilzli** [comment]
Du oder ich? @roranmorea

**Comment by roranmorea** [comment]
also ich glaub mier müend eus jetzt entscheide zwüsched 2 Vorgehe/Plän für der 1. Release:
1. Mier fixed all bugs und fehler, aber änderet so wiit als möglich nüt am system wie mers jetzt hend. D. h. mier gönd nöd go neui Logik iibaue wenn nöd nötig.
2. Mier Zeichned einmal uf Papier die ganz Logik uuf, inkl. wo weli Information ide Firebase gspeicheret wird und lueged denn was nöd "optimal" isch und vor allem chum ich eifach nümme drus, was wo gspeicheret und für was benutzt wird.
Chunnsch drus wasi meine?

**Comment by Rumpelstilzli** [comment]
glaub chum drus was du meinsch
bin für 2.
Wenn mir es App mit ere Logik a released, denk ich gits es getto wenn mir  e logik b wennd kreiere

**Comment by Rumpelstilzli** [comment]
Aber zu eme Endi cho isch au wichtig, luege mers nach dinere Prüefige mal ah?

**Comment by roranmorea** [comment]
Ja ich wär dorum meh für 1.
Wenn ja alles funktioniert, ischs ja gliich ob im Code Getto isch für de User.
Ich denke suscht müesstemer eus treffe und alles duregah und alles ufzeichne.
Das wür huere lang gah, ich denk länger wie einmal treffe und denn chunnt die App erscht ufs Pfila use.

**Comment by roranmorea** [comment]
Min Vorschlag für Message Groups wär jetzt eifach, dass mer im UserMap doch eifach en Array hend wo MessageGroups heisst und i dem bi TN's eifach bim Registriere d GroupID vo de Stufe vom TN isch und bi Eltere wird d GroupID vom Chind inetah, sobald eis verknüpft wird.

**Comment by Rumpelstilzli** [comment]
@roranmorea ja das mümmer ahluege. De Sinn vom subscribedGroups feld isch, dass mer mitglied vo mehrene gruppe si chan. Für Eltere wär das wichtig, da ihri chinder nöd zwinged ih de gliche Stufe sie münd. Zudem chömmer so eifach e neui gruppe erstelle usw. Ich bin eigentlich für das System, mer chönti sicher au das parallel mache, denk eifach das es paralles system sich am endi Komplizierter usestellt. Aber vlt sötte mer das mal zemme ahluge, ich bin glaubs e chli witer wie du denksch. S teleblitz, persone verzeichnis und d recht funktioniertet jetzt uf dem "neue" system.
