### ISSUE TITLE
Ansicht Account Registrierung:

### ISSUE THREAD

**Issue by roranmorea** [Rumpelstilzli/morea#49]
Beit TN-Registrierung wird bei Stufenauswahl nach dem Auswählen die GruppenID angezeigt und nicht der Gruppenname.
Geburtstag wird auch noch falsch angezeigt als Monat/Tag/Jahr, anstatt wie wir es sonst in der App haben Tag.Monat.Jahr.

**Comment by Rumpelstilzli** [comment]
@roranmorea Meinsch du de DateTimePicker oder im Map?
Falls DateTimePicker
--> Müsst mer mit eme Custom DateTimePicker mache, dokumentiert ischs in chinesisch.
Falls im Map
--> müsst eigentlich ahzeige
![grafik](https://user-images.githubusercontent.com/32130052/73080891-dcf96500-3ec6-11ea-8b2a-13b1bd302735.png)
