### ISSUE TITLE
Firebase rules

### ISSUE THREAD

**Issue by roranmorea** [Rumpelstilzli/morea#62]
1. Nur Functions write rights
2. Deine Usermap lesen
3. Eltern ihre kinder und umgekehrt
4. Leiter alles lesen

**Comment by Rumpelstilzli** [comment]
![grafik](https://user-images.githubusercontent.com/32130052/73948330-21d6c000-48f9-11ea-93b0-50dbb701d674.png)
bin als Vater eingeloggt

**Comment by roranmorea** [comment]
> ![grafik](https://user-images.githubusercontent.com/32130052/73948330-21d6c000-48f9-11ea-93b0-50dbb701d674.png)
> bin als Vater eingeloggt

Wele screen verursacht de Fehler?
