### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Rumpelstilzli** [Rumpelstilzli/morea#64]
Beim Registrieren eines Elternteils wird nach dem Geburtstag gefragt. Braucht es dies wirklich @roranmorea?
![grafik](https://user-images.githubusercontent.com/32130052/73824537-9f67d680-47fa-11ea-9581-6554c48382eb.png)

**Comment by roranmorea** [comment]
Also ich würde sagen nicht umbedingt. Aber wenn man es herausnimmt muss man in allen personenverzeichnissen testen gehen und allenfalls anpassungen machen, da der eintrag dann leer ist und fehler machen kann.
