### ISSUE TITLE
Datenschutz Mailchimp

### ISSUE THREAD

**Issue by roranmorea** [Rumpelstilzli/morea#74]
Ich denke wir müssen unsere User darauf Aufmerksam machen, dass sie sich beim Registrieren auch für unseren Mailchimp Verteiler einschreiben.

**Comment by Rumpelstilzli** [comment]
Das könnten wir in die Bestehende Datenschutzerklährung miteinbetten.

**Comment by roranmorea** [comment]
das wär natürlich au sehr guet
