### ISSUE TITLE
small screen sizes

### ISSUE THREAD

**Issue by roranmorea** [Rumpelstilzli/morea#79]
in small screen sizes the text is too big

**Comment by Rumpelstilzli** [comment]
Wo? und auf welchem Gerät?

**Comment by roranmorea** [comment]
probier mal es uf em iphone 5 laufe lah. aschiinends isch das s chlinschte grät wo mer hüt zu tags no hüfig benutzt. Gaht das uf dim Emulator?

**Comment by Rumpelstilzli** [comment]
Ich chans erst nechst wuche usprobiere. Luege mer mal aber falls es kein simulator het, mini mum het es Iphone 5 SE

 

Von: Massimiliano Grifone <notifications@github.com> 
Gesendet: 03 March 2020 22:52
An: Rumpelstilzli/morea <morea@noreply.github.com>
Cc: Rumpelstilzli <david_wild@gmx.ch>; Comment <comment@noreply.github.com>
Betreff: Re: [Rumpelstilzli/morea] small screen sizes (#79)

 

probier mal es uf em iphone 5 laufe lah. aschiinends isch das s chlinschte grät wo mer hüt zu tags no hüfig benutzt. Gaht das uf dim Emulator?

**Comment by Rumpelstilzli** [comment]
Hans gmacht und es paar sache behobe
