### ISSUE TITLE
Teleblitz ändern:

### ISSUE THREAD

**Issue by roranmorea** [Rumpelstilzli/morea#87]
Teleblitz ändern funktioniert nicht weill "Timpstamp has to be non-null".

**Comment by Rumpelstilzli** [comment]
Was isch de Status vo dem?

**Comment by Rumpelstilzli** [comment]
No es paar anderi Sache wo mer au muss ändere:

- Bottomsheet einbauen
- Teleblitz soll eventID nicht ändern

**Comment by roranmorea** [comment]
> No es paar anderi Sache wo mer au muss ändere:
> 
> * Bottomsheet einbauen
> * Teleblitz soll eventID nicht ändern

Sorry ich han glaub vergässe was mer vorgha hend... Was isch mit Bottomsheet gmeint?

**Comment by roranmorea** [comment]
Ich glaube de Fehler liggt drah, dass d Funktion vom Teleblitzufelade nonig uf die neu Datehyrarchie vo Events apasst isch.
@Rumpelstilzli wär das echt möglich dass du das churz machsch, wil ich chum nonig zu 100% drus wie und wo Events gspeicheret werdet.

**Comment by Rumpelstilzli** [comment]
isi, machi @roranmorea
