### ISSUE TITLE
Firestore Transaction um Kollisionen zu vermeiden.

### ISSUE THREAD

**Issue by Rumpelstilzli** [Rumpelstilzli/morea#9]
bei transaction --> t.updat /t.write hat mühe mit doc ref. App stüzt ab. Error ist PlatformException(Error performing Transaction#set, Provided document reference is from a different Friestore instance., null)

**Comment by roranmorea** [comment]
Ich kenn das Problem.
Du muesch ufpasse, dass denn wenn du im Firestore lisisch durch e Instanz vo MoreaFire, dass das die gliich Instanz isch mit dere du d Transaction machsch.

**Comment by Rumpelstilzli** [comment]
s problem isch gsi, dass mer d transaction mit em Initial instances vom firebase app mache muss.
