### ISSUE TITLE
Migrate Cloud Functions to Node 10

### ISSUE THREAD

**Issue by Rumpelstilzli** [Rumpelstilzli/morea#96]
-> Update nödig wenn kein weiteres Update gemacht werden sollte. @roranmorea  Oder was meinsch?

**Comment by roranmorea** [comment]
> -> Update nödig wenn kein weiteres Update gemacht werden sollte. @roranmorea  Oder was meinsch?

Wie meinsch das? Also find scho dass mers update söttet. D frag isch wie mer das mit em billing mached.

**Comment by Rumpelstilzli** [comment]
Ich hett es paar Idee

- Mir zahleds mit em Uftrag vo mim dad
- Mir chönted en (im kleinen Rahmen) Crowdfunding ufruehf mache
- Mir zahleds

**Comment by roranmorea** [comment]
> Ich hett es paar Idee
> 
> - Mir zahleds mit em Uftrag vo mim dad
> - Mir chönted en (im kleinen Rahmen) Crowdfunding ufruehf mache
> - Mir zahleds

Ich denk selber zahle müemers sicher ned, wils ja im moment no nur für d pfadi isch ubd dadurch dur d pfadi chennti überneh werde.
Aber d Frag isch meh mit wele chärtli. Ich han ned so bock uf mis private chärtli laufendi chöschte neh.

**Comment by Rumpelstilzli** [comment]
Mir chönted so Prepaid Kreditkarte chaufe, zb. eine vom Kiosk - was meinsch?
Ich chönti's au uf mini Prepaid Karte laufe lah, aber denk wer besser wenn ali druf zuegriff hettet.
